project:
  type: website
  output-dir: docs
  execute-dir: project
  
website:
  title: "The Human Side of Shipping"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tab-one/tab-one-index.qmd
        text: Tab title
      - href: tab-presentation/presentation-index.qmd
        text: Presentations        
      - href: tab-iframe/iframe-index.qmd
        text: Shipping survey
      - href: survey_data.qmd 
        text: "Survey Data"
    logo: images/logo_tepak.png
       
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


